'use strict';
(() => {
 const $=id=>document.getElementById(id);
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const bank=window.EXAMS.flatMap((set,s)=>set.map((q,i)=>({...q,id:`${s+1}-${i+1}`,set:s,chapter:Number((q.src.match(/Bài (\d)/)||[])[1]||0)})));
 const byId=new Map(bank.map(q=>[q.id,q]));
 const STORE='sql-huce-200-v1';
 let saved={}, storageAvailable=true;
 try{saved=JSON.parse(localStorage.getItem(STORE)||'{}')||{};}catch{storageAvailable=false;}
 let wrong=new Set((saved.wrong||[]).filter(id=>byId.has(id))), flags=new Set((saved.flags||[]).filter(id=>byId.has(id)));
 let mode='practice', current=null, pending=null, toastTimer;
 function validAttempt(a){return a && Array.isArray(a.ids) && a.ids.length>0 && a.ids.every(id=>byId.has(id)) && new Set(a.ids).size===a.ids.length && ['practice','exam'].includes(a.mode) && Array.isArray(a.answers) && a.answers.length===a.ids.length && a.answers.every(x=>x===null || (Number.isInteger(x)&&x>=0&&x<4)) && Number.isInteger(a.index) && a.index>=0 && a.index<a.ids.length && Number.isFinite(a.started) && (a.deadline===null || Number.isFinite(a.deadline));}
 if(validAttempt(saved.attempt))current=saved.attempt;
 document.body.classList.toggle('dark',saved.theme==='dark');
 function persist(){try{localStorage.setItem(STORE,JSON.stringify({wrong:[...wrong],flags:[...flags],theme:document.body.classList.contains('dark')?'dark':'light',attempt:current}));}catch{if(storageAvailable)toast('Không lưu được tiến độ. Bạn vẫn có thể làm bài trong phiên này.');storageAvailable=false;}}
 function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
 function shuffled(array){const a=[...array];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 function stats(){ $('wrong-count').textContent=wrong.size;$('flag-count').textContent=flags.size;$('study-wrong').disabled=!wrong.size;$('study-flagged').disabled=!flags.size;$('resume').hidden=!current;$('resume').textContent=current?.finished?'Xem lại kết quả gần nhất':'Tiếp tục bài đang làm'; }
 function setting(){ $('practice-mode').classList.toggle('active',mode==='practice');$('exam-mode').classList.toggle('active',mode==='exam');$('practice-mode').setAttribute('aria-pressed',mode==='practice');$('exam-mode').setAttribute('aria-pressed',mode==='exam');$('time-field').hidden=mode!=='exam';$('random-settings').hidden=$('set').value!=='random';$('start').textContent=mode==='practice'?'Bắt đầu luyện tập':'Bắt đầu thi thử'; const random=$('set').value==='random';let amount=40;if(random){const pool=bank.filter(q=>$('chapter').value==='all'||q.chapter===Number($('chapter').value));amount=$('count').value==='all'?pool.length:Math.min(Number($('count').value),pool.length);}let time=$('duration').value==='auto'?`${amount*75/60} phút`:$('duration').value==='none'?'Không giới hạn':`${$('duration').value} phút`; $('setting-hint').textContent=`${amount} câu · ${mode==='practice'?'Xem đáp án ngay sau khi chọn.':time+' · Nộp bài mới hiện đáp án.'}`; }
 function ask(title,body,label,action){pending=action;$('confirm-title').textContent=title;$('confirm-body').textContent=body;$('confirm-ok').textContent=label;$('confirm').showModal();}
 $('cancel').onclick=()=>{$('confirm').close();pending=null;};
 $('confirm-ok').onclick=()=>{const action=pending;pending=null;$('confirm').close();if(action)action();};
 $('confirm').addEventListener('cancel',()=>pending=null);
 function run(ids,label,selectedMode=mode){if(!ids.length){toast('Chưa có câu hỏi trong danh sách này.');return;} const create=()=>{const duration=$('duration').value;const seconds=selectedMode==='exam'?(duration==='auto'?ids.length*75:duration==='none'?null:Number(duration)*60):null;current={ids,answers:ids.map(()=>null),index:0,mode:selectedMode,label,started:Date.now(),deadline:seconds===null?null:Date.now()+seconds*1000,finished:false,completed:null};persist();showQuiz();};if(current&&!current.finished)ask('Bắt đầu bài mới?','Bài đang làm sẽ được thay bằng lượt mới. Danh sách câu sai và đánh dấu vẫn giữ lại.','Bắt đầu bài mới',create);else create();}
 function start(){const value=$('set').value;if(value==='random'){let pool=bank.filter(q=>$('chapter').value==='all'||q.chapter===Number($('chapter').value));pool=shuffled(pool);const count=$('count').value==='all'?pool.length:Number($('count').value);run(pool.slice(0,count).map(q=>q.id),$('chapter').value==='all'?'Đề ngẫu nhiên':`Ôn bài ${$('chapter').value}`);}else run(bank.filter(q=>q.set===Number(value)).map(q=>q.id),`Đề ${String(Number(value)+1).padStart(2,'0')}`);}
 function showQuiz(){ $('setup').hidden=true;$('quiz').hidden=false;$('quiz-title').textContent=`${current.label} · ${current.mode==='practice'?'Luyện tập':'Thi thử'}`;render();window.scrollTo({top:0,behavior:'instant'}); }
 function home(){persist();stats();$('quiz').hidden=true;$('setup').hidden=false;window.scrollTo({top:0,behavior:'instant'});}
 function countAnswered(){return current.answers.filter(x=>x!==null).length;}
 function availableFeedback(){return current.finished || current.mode==='practice';}
 function showResults(){if(!current.finished){$('results').hidden=true;return;}const total=current.ids.length;const correct=current.ids.filter((id,i)=>current.answers[i]===byId.get(id).options.indexOf(byId.get(id).correct)).length;const blank=total-countAnswered();const elapsed=Math.max(0,Math.floor(((current.completed||Date.now())-current.started)/1000));$('results').innerHTML=`<div class="score">${(correct/total*10).toFixed(2)}<small> / 10</small></div><div class="result-detail"><div class="result-title">${current.autoFinished?'Hết giờ · Đã nộp bài':'Đã hoàn thành'}</div>${correct}/${total} câu đúng · ${total-correct-blank} câu sai · ${blank} câu bỏ trống<br>Thời gian: ${Math.floor(elapsed/60)} phút ${elapsed%60} giây</div><div class="result-actions"><button class="button" id="review-mistakes">Xem câu sai</button><button class="button" id="new-set">Chọn đề khác</button></div>`;$('results').hidden=false;$('review-mistakes').onclick=()=>{const index=current.ids.findIndex((id,i)=>current.answers[i]!==byId.get(id).options.indexOf(byId.get(id).correct));if(index===-1)toast('Bạn đã trả lời đúng tất cả các câu.');else go(index);};$('new-set').onclick=home;}
 function render(){const q=byId.get(current.ids[current.index]);const chosen=current.answers[current.index],correct=q.options.indexOf(q.correct),reveal=availableFeedback()&&(chosen!==null||current.finished);$('question-position').textContent=`CÂU ${String(current.index+1).padStart(2,'0')} / ${current.ids.length}`;$('topic').textContent=`Bài ${q.chapter} · ${q.topic}`;$('question-stem').textContent=q.stem;$('question-code').textContent=q.code;$('code').hidden=!q.code;$('flag').classList.toggle('on',flags.has(q.id));$('flag').setAttribute('aria-pressed',flags.has(q.id));$('flag').textContent=flags.has(q.id)?'★ Đã đánh dấu':'☆ Đánh dấu';$('options').innerHTML=q.options.map((text,i)=>`<button class="option ${chosen===i?'selected':''} ${reveal&&i===correct?'correct':''} ${reveal&&chosen===i&&i!==correct?'wrong':''}" data-choice="${i}" aria-pressed="${chosen===i}" ${current.finished || (current.mode==='practice'&&chosen!==null)?'disabled':''}><span class="option-letter">${'ABCD'[i]}</span><span>${escape(text)}</span></button>`).join('');$('options').querySelectorAll('[data-choice]').forEach(button=>button.onclick=()=>choose(Number(button.dataset.choice)));
 $('feedback').hidden=!reveal;if(reveal)$('feedback').innerHTML=`<strong>${chosen===correct?'Đúng.':chosen===null?'Chưa trả lời.':'Chưa đúng.'} Đáp án ${'ABCD'[correct]}</strong><p>${escape(q.explain)}</p><small>Đối chiếu: ${escape(q.src)}</small>`;
 $('prev').disabled=current.index===0;$('next').textContent=current.index===current.ids.length-1?(current.finished?'Đã xem hết':'Hoàn thành'):'Câu tiếp';$('next').disabled=current.finished&&current.index===current.ids.length-1;$('answered').textContent=`${countAnswered()}/${current.ids.length}`;$('answered-small').textContent=`${countAnswered()} đã làm`;$('progress-fill').style.width=`${100*countAnswered()/current.ids.length}%`;
 $('palette').innerHTML=current.ids.map((id,i)=>{const item=byId.get(id),answer=current.answers[i],exposed=availableFeedback()&&(answer!==null||current.finished),right=answer===item.options.indexOf(item.correct);const classes=[i===current.index?'current':'',answer!==null?'answered':'',flags.has(id)?'flagged':'',exposed?(right?'right':'incorrect'):''].join(' ');let status=exposed?(right?'đúng':answer===null?'bỏ trống':'sai'):answer!==null?'đã làm':'chưa làm';return `<button data-index="${i}" class="${classes}" aria-label="Câu ${i+1}, ${status}${flags.has(id)?', đã đánh dấu':''}" ${i===current.index?'aria-current="step"':''}>${i+1}</button>`;}).join('');$('palette').querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>go(Number(b.dataset.index)));$('submit').hidden=current.finished;$('restart').hidden=!current.finished;$('submit').textContent=current.mode==='practice'?'Kết thúc lượt luyện':'Nộp bài';showResults();updateTimer(); }
 function choose(index){if(current.finished || (current.mode==='practice'&&current.answers[current.index]!==null))return;current.answers[current.index]=index;if(current.mode==='practice'){const q=byId.get(current.ids[current.index]);if(q.options[index]===q.correct)wrong.delete(q.id);else wrong.add(q.id);}persist();render();}
 function go(index){if(index<0||index>=current.ids.length)return;current.index=index;persist();render();const el=$('question-stem');el.setAttribute('tabindex','-1');el.focus({preventScroll:true});$('quiz-title').scrollIntoView({behavior:'instant',block:'start'});}
 function requestFinish(){const blanks=current.ids.length-countAnswered();ask(current.mode==='exam'?'Nộp bài thi thử?':'Kết thúc lượt luyện?',blanks?`Bạn còn ${blanks} câu chưa trả lời. Các câu bỏ trống được tính 0 điểm.`:'Bạn đã trả lời tất cả các câu. Xem điểm và giải thích sau khi kết thúc.',current.mode==='exam'?'Nộp bài':'Xem kết quả',()=>finish(false));}
 function finish(auto){if(!current||current.finished)return;current.finished=true;current.completed=auto&&current.deadline?current.deadline:Date.now();current.autoFinished=auto;for(let i=0;i<current.ids.length;i++){const q=byId.get(current.ids[i]);if(current.answers[i]===q.options.indexOf(q.correct))wrong.delete(q.id);else wrong.add(q.id);}if($('confirm').open){$('confirm').close();pending=null;}persist();showQuiz();}
 function updateTimer(){if(!current)return;const active=current.mode==='exam'&&current.deadline!==null&&!current.finished;$('timer').hidden=!active;if(!active)return;const remaining=Math.max(0,Math.ceil((current.deadline-Date.now())/1000));$('timer').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;$('timer').classList.toggle('warning',remaining<=300);if(remaining===0)finish(true);}
 $('practice-mode').onclick=()=>{mode='practice';setting();};$('exam-mode').onclick=()=>{mode='exam';setting();};['set','chapter','count','duration'].forEach(id=>$(id).onchange=setting);$('start').onclick=start;$('resume').onclick=()=>{if(current)showQuiz();};$('theme').onclick=()=>{document.body.classList.toggle('dark');persist();};$('brand').onclick=e=>{e.preventDefault();home();};$('back-setup').onclick=home;$('prev').onclick=()=>go(current.index-1);$('next').onclick=()=>current.index<current.ids.length-1?go(current.index+1):requestFinish();$('flag').onclick=()=>{const id=current.ids[current.index];if(flags.has(id))flags.delete(id);else flags.add(id);persist();render();};$('submit').onclick=requestFinish;$('restart').onclick=()=>run([...current.ids],current.label,current.mode);$('study-wrong').onclick=()=>run([...wrong],'Ôn câu sai','practice');$('study-flagged').onclick=()=>run([...flags],'Ôn câu đánh dấu','practice');
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)updateTimer();});window.addEventListener('pagehide',persist);setInterval(updateTimer,1000);
 stats();setting();if(current&&!current.finished){toast('Có bài đang làm. Bấm Tiếp tục để mở lại.');updateTimer();}
})();
